version: "0.0.1.{build}"
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017

environment:
  COVERALLS_REPO_TOKEN:
    secure: EpNdzj3IQUSrXiz0O1EGjAwPV5AhZJy1XovtymuCMqIYbj3ziJAY1OcjRwfkt5DG
install:
  - git submodule update --init --recursive
  - nuget restore TheFlow.Core.sln
nuget:
  disable_publish_on_pr: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

build_script:
- ps: .\Build.ps1
test: off
artifacts:
- path: .\src\TheFlow\artifacts\**\*.nupkg
  name: NuGet

deploy:
- provider: NuGet
  api_key:
    secure: NKrMxQUn7fqteI+uf4gFMpitYZPVX4H1fAkzAJQA+SYl6dnhyu3VyZLufigRJBZp
  skip_symbols: true
  on:
    branch: master

after_build:
  - >
      %userprofile%\.nuget\packages\coveralls.io\1.4.2\tools\coveralls.net.exe --opencover test/coverage.xml -r  %COVERALLS_REPO_TOKEN%
